export const en = {
  navigation: {
    tableauDeBord: "Dashboard",
    utilisateurs: "Users",
    credits: "Credits",
    epargnes: "Savings",
    transactions: "Transactions",
    rapports: "Reports & Statistics",
    aide: "Help",
    parametres: "Settings",
  },
  tableauDeBord: {
    titre: "Dashboard",
    evolutionDesc: "Credits, savings and transactions over 6 months",
    cinqDernieresOperations: "Last 5 operations",
    cinqDerniersMicroCredits: "Last 5 microloans",
    description: "Welcome to your dashboard — here is an overview of platform activity.",
    totalUtilisateurs: "Total Users",
    commercantsInscrits: "Registered merchants",
    creditsActifs: "Active Credits",
    pretsEnCours: "Ongoing loans",
    epargnesActives: "Active Savings",
    comptesEpargne: "Savings accounts",
    transactionsAujourdhui: "Today's Transactions",
    canalsMobile: "Orange Money & MTN",
    revenusTotal: "Total Revenue",
    ceMois: "This month",
    tauxRemboursement: "Repayment Rate",
    sixDerniersMois: "Over the last 6 months",
    evolutionActivites: "Activity Evolution (last 6 months)",
    dernieresTransactions: "Latest Transactions",
    creditsRecents: "Recent Credits",
  },
  utilisateurs: {
    titre: "Users",
    description: "Manage merchants registered on the platform.",
    recherche: "Search by name, phone or city...",
    tousStatuts: "All statuses",
    nom: "Name",
    telephone: "Phone",
    ville: "City",
    epargne: "Savings",
    credits: "Credits",
    statut: "Status",
    actions: "Actions",
    aucunUtilisateur: "No user found.",
    voir: "View",
    actif: "Active",
    inactif: "Inactive",
    suspendu: "Suspended",
    suspendre: "Suspend",
    activer: "Activate",
    profil: "Profile of",
    membreDepuis: "Member since",
    informationsPersonnelles: "Personal information",
    donneesFinancieres: "Financial data",
    epargnetotale: "Total savings",
    creditsActifs: "Active credits",
    fermerProfil: "Close profile",
    inscription: "Registration",
  },
  credits: {
    titre: "Credits",
    rejete: "Rejected",
    description: "Manage microloans granted to merchants.",
    recherche: "Search by name...",
    tousStatuts: "All statuses",
    totalCredits: "Total Credits",
    totalRembourse: "Total Repaid",
    enAttente: "Pending",
    enRetard: "Overdue",
    commercant: "Merchant",
    montant: "Amount",
    rembourse: "Repaid",
    taux: "Rate",
    echeance: "Due Date",
    actions: "Actions",
    aucunCredit: "No credit found.",
    approuver: "Approve",
    rejeter: "Reject",
    actif: "Active",
    rembourse_statut: "Repaid",
    enAttente_statut: "Pending",
    enRetard_statut: "Overdue",
    confirmationApprouver: "Confirm approval",
    confirmationRejeter: "Confirm rejection",
    confirmationTexte: "This action cannot be undone.",
    confirmer: "Confirm",
    annuler: "Cancel",
    approuverSousTitre: "This action will release the funds",
    approuverIntro: "You are about to approve the following request:",
    rejeterIntro: "You are about to reject the following request:",
    approuverAvertissement: "Funds will be released within 24h via Orange Money or MTN Mobile Money.",
    rejeterAvertissement: "The rejection will notify the merchant. This action cannot be undone.",
    confirmerApprobation: "Confirm approval",
    confirmerRejet: "Confirm rejection",
    tauxInteret: "Interest rate",
    mois: "month",
    demandes: "request(s)",
    creditsLabel: "credit(s)",
    statut: "Status",
  },
  epargnes: {
    titre: "Savings",
    description: "Track merchant savings accounts.",
    recherche: "Search by name...",
    totalEpargnes: "Total Savings",
    epargnants: "Savers",
    moyenneParCompte: "Average per account",
    totalDepots: "Total Deposits",
    meilleurEpargnant: "🏆 Best saver of the month",
    typeEpargne: "Savings type",
    solde: "Balance",
    progression: "Progress",
    nbDepots: "Nb. Deposits",
    dernierDepot: "Last Deposit",
    aucuneEpargne: "No savings found.",
    objectif: "Goal",
    tousTypes: "All types",
    quotidienne: "Daily",
    hebdomadaire: "Weekly",
  },
  transactions: {
    titre: "Transactions",
    description: "Track all financial operations on the platform.",
    recherche: "Search by name...",
    totalDepots: "Total Deposits",
    totalTransferts: "Total Transfers",
    totalRetraits: "Total Withdrawals",
    remboursements: "Repayments",
    commercant: "Merchant",
    type: "Type",
    montant: "Amount",
    canal: "Channel",
    date: "Date",
    statut: "Status",
    aucuneTransaction: "No transaction found.",
    depot: "Deposit",
    retrait: "Withdrawal",
    transfert: "Transfer",
    remboursement: "Repayment",
    reussi: "Successful",
    echoue: "Failed",
    enAttente: "Pending",
    tousTypes: "All types",
    tousCanaux: "All channels",
  },
  rapports: {
    titre: "Reports & Analytics",
    exporter: "Export",
    sixMois: "6 months",
    volumeCredits: "Credit Volume",
    totalMicroCredits: "Total microloans",
    totalEpargnes: "Total Savings",
    soldeCumule: "Cumulative savers balance",
    volumeTransactions: "Transaction Volume",
    toutesOperations: "All operations combined",
    tauxReussite: "Success Rate",
    repartitionCredits: "Credit Breakdown",
    parStatutRemboursement: "By repayment status",
    canauxPaiement: "Payment Channels",
    canauxDesc: "Orange Money vs MTN Mobile Money",
    nbTransactions: "Nb. Transactions",
    montantFCFA: "Amount (FCFA)",
    creditLabel: "credit(s)",
    tauxRemboursement: "Repayment rate",
    transactionsReussies: "Successful transactions",
    epargneReguliere: "Regular savings",
    creditsEnRetard: "Overdue credits",
    description: "Platform performance overview — January 2025",
    exporterRapport: "Export report",
    exporterPDF: "Export as PDF",
    exporterExcel: "Download Excel table",
    chiffresCles: "📊 Key Figures",
    chiffresClesDesc: "Global summary of platform activity",
    evolutionActivites: "📈 Activity Evolution",
    evolutionDesc: "Trends over the last 6 months",
    analyseDetaillee: "🔍 Detailed Analysis",
    analyseDesc: "Credit breakdown and payment channels",
    indicateurs: "🎯 Performance Indicators",
    indicateursDesc: "Key platform rates",
  },
  parametres: {
    titre: "Settings",
    description: "Manage your profile and platform preferences.",
    profil: "Profile",
    notifications: "Notifications",
    application: "Application",
    sauvegarderProfil: "Save profile",
    modifierMotDePasse: "Change password",
    sauvegarderNotifications: "Save notifications",
    sauvegarderParametres: "Save settings",
    langue: "Interface language",
    devise: "Currency",
    modifier: "Edit",
    annuler: "Cancel",
    sauvegarder: "Save",
    modeProfil: "Edit your personal information.",
    modeProfilLecture: "View your personal information.",
    nomComplet: "Full name",
    email: "Email",
    telephone: "Phone",
    motDePasse: "Password",
    motDePasseDesc: "Secure your administrator access.",
    motDePasseEdition: "Change your password.",
    motDePasseActuel: "Current password",
    ancienMotDePasse: "🔑 Current password",
    nouveauMotDePasse: "🆕 New password",
    confirmerMotDePasse: "✅ Confirm password",
    reglesMotDePasse: "📋 Password rules",
    regle1: "✅ Minimum 6 characters",
    regle2: "✅ Different from old password",
    regle3: "✅ Confirmation must match",
    enLigne: "Online",
    parametresProfil: "Profile settings",
    seDeconnecter: "Sign out",
    apparence: "🎨 Appearance",
    modeSombre: "Dark Mode",
    modeClair: "Light Mode",
    interfaceSombre: "Dark interface enabled",
    interfaceClaire: "Light interface enabled",
    infoPlateforme: "ℹ️ Platform information",
    version: "Version",
    environnement: "Environment",
    derniereMaj: "Last update",
    avertissementLangue: '⚠️ Changes will apply after clicking "Save".',
    choisirAvatar: "🎭 Choose your avatar",
    changerAvatar: "🎨 Change avatar",
    fermer: "✕ Close",
    notificationsDesc: "Choose the alerts you want to receive.",
    applicationDesc: "Configure the theme, language and currency.",
    notifNouveauCredit: "New credit request",
    notifNouveauCreditDesc: "Alerts for each new request",
    notifRemboursement: "Repayment received",
    notifRemboursementDesc: "Confirm received payments",
    notifRetard: "Overdue credit",
    notifRetardDesc: "Alerts for late payments",
    notifNouvelUtilisateur: "New user registered",
    notifNouvelUtilisateurDesc: "Notification for each registration",
    notifRapportHebdo: "Weekly report",
    notifRapportHebdoDesc: "Automatic weekly summary",
  },
  commun: {
    actif: "Active",
    adminDashboard: "Admin Dashboard",
    rechercher: "Search...",
    enAttente: "Pending",
    enCours: "Active",
    enRetard: "Overdue",
    rembourse: "Repaid",
    suspendu: "Suspended",
    oui: "Yes",
    non: "No",
    locale: "en-GB",
    masquer: "Hide",
    afficher: "Show",
    fermerMenu: "Close menu",
    menuPrincipal: "Main menu",
    ouvrirMenu: "Open menu",
    menuProfil: "Profile menu",
    administrateur: "Administrator",
    notificationsNonLues: "unread notifications",
    bonjour: "Good morning",
    bonApresMidi: "Good afternoon",
    bonsoir: "Good evening",
    filtrer: "Filter",
    total: "total",
    trouve: "found",
    sur: "of",
    excellent: "✅ Excellent",
    satisfaisant: "⚠️ Satisfactory",
    ameliorer: "❌ Needs improvement",
    modifier: "Edit",
    annuler: "Cancel",
    sauvegarder: "Save",
    confirmer: "Confirm",
    fermer: "Close",
    voir: "View",
    succes: "Success",
    erreur: "Error",
    chargement: "Loading...",
    aucunResultat: "No results found.",
    profil: "Profile",
    deconnexion: "Sign out",
  },
  aide: {
    titre: "Help Center",
    description: "Complete guide to using the MicroFinance Admin platform",
    recherche: "Search help...",
    demarrage: "Getting Started",
    gestionUtilisateurs: "Users",
    gestionCredits: "Credits",
    gestionEpargnes: "Savings",
    gestionTransactions: "Transactions",
    gestionParametres: "Settings",
    faq: "FAQ",
    astuce: "💡 Tip",
    important: "⚠️ Important",
    etape: "Step",
    demarrageTitre: "Welcome to MicroFinance Admin",
    démarrageDesc: "This platform allows you to manage all microfinance operations for informal traders in Cameroon.",
    simulationTDB: "Dashboard — MicroFinance Admin",
    simulationBonjour: "Hi, Admin",
    simulationDate: "Dashboard — Tuesday March 10",
    etapesDemarrage: "Getting started steps",
    etape1Titre: "Log in to your account",
    etape1Desc: "Enter your email and password on the login page.",
    etape2Titre: "Explore the dashboard",
    etape2Desc: "The dashboard displays key stats: users, active credits, savings and today's transactions.",
    etape3Titre: "Navigate via the menu",
    etape3Desc: "Use the left sidebar to access the different sections. The logout button is at the bottom of this sidebar.",
    etape4Titre: "Customize the interface",
    etape4Desc: "In Settings, enable dark mode, change the language and update your profile.",
    vueEnsemble: "Sections overview",
    vueUtilisateurs: "Manage registered traders",
    vueCredits: "Approve or reject requests",
    vueEpargnes: "Track savings accounts",
    vueTransactions: "Orange Money / MTN history",
    astuceDeMarrage: "Check the dashboard every morning to get an overview of yesterday's activity.",
    utilisateursDesc: "This section lets you view and manage all traders registered on the platform.",
    actionsDisponibles: "Available actions",
    uEtape1Titre: "Search for a user",
    uEtape1Desc: "Use the search bar to find a trader by name.",
    uEtape2Titre: "Filter by status",
    uEtape2Desc: "Filter the list by status: Active, Inactive or Suspended.",
    uEtape3Titre: "View profile",
    uEtape3Desc: "Click 'View' to see a trader's full details.",
    uEtape4Titre: "Suspend / Activate",
    uEtape4Desc: "Use the 'Suspend' button to temporarily block an account, or 'Activate' to reactivate it.",
    importantUtilisateurs: "Suspending an account prevents the trader from accessing their services. Make sure you have a valid reason before suspending an account.",
    astuceUtilisateurs: "Check the 'Suspended' filter regularly to review accounts that need attention.",
    creditsDesc: "Manage microcredit requests from traders (20,000 — 200,000 FCFA).",
    processusApprobation: "Approval process",
    cEtape1Titre: "Identify pending requests",
    cEtape1Desc: "Filter by 'Pending' status to see all new requests to process.",
    cEtape2Titre: "Check the information",
    cEtape2Desc: "Review the requested amount, interest rate and due date.",
    cEtape3Titre: "Approve or reject",
    cEtape3Desc: "Click 'Approve' or 'Reject'. A confirmation modal appears with the details.",
    cEtape4Titre: "Confirmation",
    cEtape4Desc: "Confirm your decision. Funds are released within 24h via Orange Money or MTN Mobile Money.",
    statutEnCoursDesc: "Active credit currently being repaid",
    statutEnAttenteDesc: "Request awaiting approval",
    statutEnRetardDesc: "Late repayment — action required",
    statutRembourseDesc: "Credit fully repaid",
    importantCredits: "Late credits must be prioritized. Contact the trader concerned to find a solution.",
    epargnesDesc: "Track traders' savings accounts — daily or weekly.",
    comprendreEpargnes: "Understanding savings types",
    eEtape1Titre: "Daily savings",
    eEtape1Desc: "The trader makes a deposit every day. Ideal for small traders with daily income.",
    eEtape2Titre: "Weekly savings",
    eEtape2Desc: "The trader makes a deposit every week. Suited to weekly sales cycles.",
    eEtape3Titre: "Progress tracking",
    eEtape3Desc: "The progress bar shows the percentage reached towards the maximum target of 200,000 FCFA.",
    eEtape4Titre: "Top saver",
    eEtape4Desc: "The golden banner highlights the trader with the highest savings balance.",
    astuceEpargnes: "Encourage traders to maintain regular savings — it improves their credit score.",
    transactionsDesc: "View the history of all operations via Orange Money and MTN Mobile Money.",
    typesTransactions: "Transaction types",
    depotDesc: "Money deposited into the account",
    retraitDesc: "Money withdrawn from the account",
    transfertDesc: "Money sent between accounts",
    remboursementDesc: "Credit repayment",
    canauxPaiement: "Payment channels",
    canalPrincipal: "Primary payment channel",
    canalSecondaire: "Secondary payment channel",
    astuceTransactions: "Use the double filter (type + channel) to quickly analyze performance by payment channel.",
    parametresDesc: "Customize your experience on the platform.",
    pProfil: "Profile",
    pProfilDesc: "Edit your name and email from the Profile tab in edit mode.",
    pModeSombre: "Dark mode",
    pModeSombreDesc: "Enable the dark theme from the Application tab.",
    pLangue: "Language",
    pLangueDesc: "Choose between Français, English and Pidgin from the Application tab.",
    pDeconnexion: "Logout",
    pDeconnexionDesc: "Log out via the button at the bottom of the left sidebar or via the profile menu at the top right.",
    changerMotDePasse: "Change password",
    pEtape1Titre: "Go to the Profile tab",
    pEtape1Desc: "In Settings, click on the 'Profile' tab.",
    pEtape2Titre: "Enable edit mode",
    pEtape2Desc: "Click 'Edit' to switch to edit mode.",
    pEtape3Titre: "Change the password",
    pEtape3Desc: "Click 'Change password', enter the old then the new password (min. 6 characters).",
    pEtape4Titre: "Save",
    pEtape4Desc: "Click 'Save' to confirm the changes.",
    deconnexion: "Log out",
    deconnexionDesc: "You can log out in two ways: via the 'Log out' button (LogOut icon) at the bottom of the left sidebar, or via the profile menu at the top right of the dashboard.",
    importantParametres: "Use a strong and unique password to secure your administrator account.",
    faqDesc: "Find answers to the most frequently asked questions.",
    faq1Q: "How do I log in to the platform?",
    faq1R: "Go to the login page, enter your email and password.",
    faq2Q: "How do I approve a credit request?",
    faq2R: "On the Credits page, filter by 'Pending'. Click 'Approve' next to the request. A confirmation modal appears — confirm to validate.",
    faq3Q: "How do I log out?",
    faq3R: "Two ways: click the 'Log out' button (LogOut icon) at the bottom of the left sidebar, or open the profile menu at the top right and click 'Log out'.",
    faq4Q: "How do I enable dark mode?",
    faq4R: "Go to Settings → Application tab. Enable the 'Dark mode' toggle. The change is immediate and saved after reload.",
    faq5Q: "How do I change the interface language?",
    faq5R: "Go to Settings → Application tab. Select Français, English or Pidgin from the Language menu.",
    faq6Q: "What if a trader doesn't repay their credit?",
    faq6R: "Identify 'Overdue' credits on the Credits page. Check the trader's info on the Users page. If necessary, suspend their account.",
    faq7Q: "How do I export reports?",
    faq7R: "On the Reports page, click 'Export report' to download as PDF or Excel (CSV).",
    resultatsRecherche: "Results for",
    sections: "Sections",
    aucunResultat: "No results found for this search.",
    besoinAide: "Need more help?",
    contactSupport: "Contact technical support: support@microfinance.com",
  },
  erreurs: {
    champVide: "This field cannot be empty.",
    emailInvalide: "Invalid email address.",
    motDePasseCourt: "Password must be at least 6 characters.",
    motDePasseIncorrect: "Current password is incorrect.",
    motDePasseNonCorrespondant: "Passwords do not match.",
    champsManquants: "Please fill in all fields.",
    profilMisAJour: "✅ Profile updated successfully!",
    motDePasseModifie: "✅ Password changed successfully!",
    notificationsSauvegardees: "✅ Notification preferences saved!",
    parametresSauvegardes: "✅ Application settings saved!",
    erreurGenerale: "❌ An error occurred.",
  },
  auth: {
    titreConnexion: "MicroFinance Admin",
    sousTitreConnexion: "Secure administrator space",
    adresseEmail: "Email address",
    motDePasse: "Password",
    seConnecter: "Sign in",
    connexionEnCours: "Signing in...",
    accesReserve: "Access reserved for administrators",
    telephone: "Phone number",
     champsObligatoires: "Please fill in all fields.",
  },
  notifications: {
    nouveauCredit: "New credit pending",
    creditRetard: "Overdue credit",
    nouvelUtilisateur: "New user registered",
    transactionEchouee: "Transaction failed",
    toutLire: "Read all",
    notifications: "Notifications",
    vientDeSInscrire: "just registered from",
    ilYa: "ago",
    minute: "minute",
    minutes: "minutes",
    heure: "hour",
    heures: "hours",
    jour: "day",
    jours: "days",
    maintenant: "now",
  },
};

export type LangueEn = typeof en;
export default en;