export const fr = {
    navigation: {
        tableauDeBord: "Tableau de bord",
        utilisateurs: "Utilisateurs",
        credits: "Crédits",
        epargnes: "Épargnes",
        transactions: "Transactions",
        rapports: "Rapports & Statistiques",
        aide: "Aide",
        parametres: "Paramètres",
        agentsTerrain: "Agents de terrain",
    },
    tableauDeBord: {
        titre: "Tableau de bord",
        evolutionDesc: "Crédits, épargnes et transactions sur 6 mois",
        cinqDernieresOperations: "5 dernières opérations",
        cinqDerniersMicroCredits: "5 derniers microcrédits",
        description: "Bienvenue sur votre tableau de bord — voici un aperçu de l'activité de la plateforme.",
        totalUtilisateurs: "Total Utilisateurs",
        commercantsInscrits: "Commerçants inscrits",
        creditsActifs: "Crédits Actifs",
        pretsEnCours: "Prêts en cours",
        epargnesActives: "Épargnes Actives",
        comptesEpargne: "Comptes d'épargne",
        transactionsAujourdhui: "Transactions Aujourd'hui",
        canalsMobile: "Orange Money & MTN",
        revenusTotal: "Revenus Total",
        ceMois: "Ce mois-ci",
        tauxRemboursement: "Taux de Remboursement",
        sixDerniersMois: "Sur les 6 derniers mois",
        evolutionActivites: "Évolution des activités (6 derniers mois)",
        dernieresTransactions: "Dernières Transactions",
        creditsRecents: "Crédits Récents",
    },
    utilisateurs: {
        nouveau: "Nouveau",
        desactiver: "Désactiver",
        bloquer: "Bloquer",
        supprimer: "Supprimer",
        confirmerActiver: "Activer l'utilisateur ?",
        confirmerDesactiver: "Désactiver l'utilisateur ?",
        confirmerBloquer: "Bloquer l'utilisateur ?",
        confirmerSupprimer: "Supprimer l'utilisateur ?",
        confirmationActiver: "L'utilisateur pourra se connecter et utiliser les services.",
        confirmationDesactiver: "L'utilisateur ne pourra plus se connecter.",
        confirmationBloquer: "L'utilisateur sera bloqué définitivement.",
        confirmationSupprimer: "Cette action est irréversible.",
        bloque: "Bloqué",
        titre: "Utilisateurs",
        description: "Gestion des commerçants inscrits sur la plateforme.",
        recherche: "Rechercher par nom, téléphone ou ville...",
        tousStatuts: "Tous les statuts",
        nom: "Nom",
        telephone: "Téléphone",
        ville: "Ville",
        epargne: "Épargne",
        credits: "Crédits",
        statut: "Statut",
        actions: "Actions",
        aucunUtilisateur: "Aucun utilisateur trouvé.",
        voir: "Voir",
        actif: "Actif",
        inactif: "Inactif",
        suspendu: "Suspendu",
        suspendre: "Suspendre",
        activer: "Activer",
        profil: "Profil de",
        membreDepuis: "Membre depuis",
        informationsPersonnelles: "Informations personnelles",
        donneesFinancieres: "Données financières",
        epargnetotale: "Épargne totale",
        creditsActifs: "Crédits actifs",
        fermerProfil: "Fermer le profil",
        inscription: "Inscription",
    },
    credits: {
        titre: "Crédits",
        rejete: "Rejeté",
        description: "Gestion des microcrédits accordés aux commerçants.",
        recherche: "Rechercher par nom...",
        tousStatuts: "Tous les statuts",
        totalCredits: "Total Crédits",
        totalRembourse: "Total Remboursé",
        enAttente: "En Attente",
        enRetard: "En Retard",
        commercant: "Commerçant",
        montant: "Montant",
        rembourse: "Remboursé",
        taux: "Taux",
        echeance: "Échéance",
        actions: "Actions",
        aucunCredit: "Aucun crédit trouvé.",
        approuver: "Approuver",
        rejeter: "Rejeter",
        actif: "Actif",
        rembourse_statut: "Remboursé",
        enAttente_statut: "En attente",
        enRetard_statut: "En retard",
        confirmationApprouver: "Confirmer l'approbation",
        confirmationRejeter: "Confirmer le rejet",
        confirmationTexte: "Cette action est irréversible.",
        confirmer: "Confirmer",
        annuler: "Annuler",
        approuverSousTitre: "Cette action débloquera les fonds",
        approuverIntro: "Vous êtes sur le point d'approuver la demande suivante :",
        rejeterIntro: "Vous êtes sur le point de rejeter la demande suivante :",
        approuverAvertissement: "Les fonds seront débloqués sous 24h via Orange Money ou MTN Mobile Money.",
        rejeterAvertissement: "Le rejet notifiera le commerçant. Cette action ne peut pas être annulée.",
        confirmerApprobation: "Confirmer l'approbation",
        confirmerRejet: "Confirmer le rejet",
        tauxInteret: "Taux d'intérêt",
        mois: "mois",
        demandes: "demande(s)",
        creditsLabel: "crédit(s)",
        statut: "Statut",
    },
    epargnes: {
        titre: "Épargnes",
        description: "Suivi des comptes d'épargne des commerçants.",
        recherche: "Rechercher par nom...",
        totalEpargnes: "Total Épargnes",
        epargnants: "Épargnants",
        moyenneParCompte: "Moyenne par compte",
        totalDepots: "Total Dépôts",
        meilleurEpargnant: "🏆 Meilleur épargnant du mois",
        typeEpargne: "Type d'épargne",
        solde: "Solde",
        progression: "Progression",
        nbDepots: "Nb. Dépôts",
        dernierDepot: "Dernier Dépôt",
        aucuneEpargne: "Aucune épargne trouvée.",
        objectif: "Objectif",
        tousTypes: "Tous les types",
        quotidienne: "Quotidienne",
        hebdomadaire: "Hebdomadaire",
        mensuelle: "Mensuelle",
        aucune: "Aucune",
    },
    transactions: {
        titre: "Transactions",
        description: "Suivi de toutes les opérations financières de la plateforme.",
        recherche: "Rechercher par nom...",
        totalDepots: "Total Dépôts",
        totalTransferts: "Total Transferts",
        totalRetraits: "Total Retraits",
        remboursements: "Remboursements",
        commercant: "Commerçant",
        type: "Type",
        montant: "Montant",
        canal: "Canal",
        date: "Date",
        statut: "Statut",
        aucuneTransaction: "Aucune transaction trouvée.",
        depot: "Dépôt",
        retrait: "Retrait",
        transfert: "Transfert",
        remboursement: "Remboursement",
        reussi: "Réussi",
        echoue: "Échoué",
        enAttente: "En attente",
        tousTypes: "Tous les types",
        tousCanaux: "Tous les canaux",
    },
    rapports: {
        titre: "Rapports & Analyses",
        exporter: "Exporter",
        sixMois: "6 mois",
        volumeCredits: "Volume de Crédits",
        totalMicroCredits: "Total des microcrédits",
        totalEpargnes: "Total Épargnes",
        soldeCumule: "Solde cumulé des épargnants",
        volumeTransactions: "Volume Transactions",
        toutesOperations: "Toutes opérations confondues",
        tauxReussite: "Taux de Réussite",
        repartitionCredits: "Répartition des Crédits",
        parStatutRemboursement: "Par statut de remboursement",
        canauxPaiement: "Canaux de Paiement",
        canauxDesc: "Orange Money vs MTN Mobile Money",
        nbTransactions: "Nb. Transactions",
        montantFCFA: "Montant (FCFA)",
        creditLabel: "crédit(s)",
        tauxRemboursement: "Taux de remboursement",
        transactionsReussies: "Transactions réussies",
        epargneReguliere: "Épargne régulière",
        creditsEnRetard: "Crédits en retard",
        description: "Vue d'ensemble des performances de la plateforme — Janvier 2025",
        exporterRapport: "Exporter le rapport",
        exporterPDF: "Exporter en PDF",
        exporterExcel: "Télécharger le tableau Excel",
        chiffresCles: "📊 Chiffres Clés",
        chiffresClesDesc: "Résumé global de l'activité de la plateforme",
        evolutionActivites: "📈 Évolution des Activités",
        evolutionDesc: "Tendances sur les 6 derniers mois",
        analyseDetaillee: "🔍 Analyse Détaillée",
        analyseDesc: "Répartition des crédits et canaux de paiement",
        indicateurs: "🎯 Indicateurs de Performance",
        indicateursDesc: "Taux clés de la plateforme",
    },
    parametresMicrofinance: {
        titre: "Paramètres",
        description: "Configuration des règles de la microfinance",
        soldeMinimum: "Solde minimum après retrait",
        soldeMinimumDescription: "Montant que chaque client doit conserver sur son compte après un retrait.",
        tauxEpargne: "Taux d'épargne annuel",
        tauxEpargneDescription:
            "Intérêts versés aux clients sur leur épargne. Ne peut pas dépasser le taux d'intérêt des crédits.",
        tauxInteret: "Taux d'intérêt des crédits",
        tauxInteretDescription:
            "Taux appliqué à tous les nouveaux crédits accordés. Doit rester supérieur ou égal au taux d'épargne.",
        erreurTaux: "Le taux d'épargne ne peut pas être supérieur au taux d'intérêt des crédits.",
        succes: "Paramètres mis à jour avec succès.",
        erreurSauvegarde: "Erreur lors de la sauvegarde. Veuillez réessayer.",
        derniereModification: "Dernière modification",
        modifier: "Modifier",
        valider: "Valider",
        annuler: "Annuler",
        FCFA: "FCFA",
        pourcentageParAn: "% par an",
        confirmerChangement: "Confirmer ce changement ?",
        impactGlobal:
            "Ce paramètre s'applique immédiatement à tous les nouveaux crédits et épargnes. Vérifiez la valeur avant de confirmer.",
        valeurActuelle: "Valeur actuelle",
        nouvelleValeur: "Nouvelle valeur",
        confirmer: "Confirmer",
        pourReference: "Pour référence",
    },
    commun: {
        actif: "Actif",
        adminDashboard: "Espace Administrateur",
        rechercher: "Rechercher...",
        enAttente: "En attente",
        enCours: "En cours",
        enRetard: "En retard",
        rembourse: "Remboursé",
        suspendu: "Suspendu",
        oui: "Oui",
        non: "Non",
        locale: "fr-FR",
        masquer: "Masquer",
        afficher: "Afficher",
        fermerMenu: "Fermer le menu",
        menuPrincipal: "Menu principal",
        ouvrirMenu: "Ouvrir le menu",
        menuProfil: "Menu profil",
        administrateur: "Administrateur",
        notificationsNonLues: "notifications non lues",
        bonjour: "Bonjour",
        bonApresMidi: "Bon après-midi",
        bonsoir: "Bonsoir",
        filtrer: "Filtrer",
        total: "total",
        trouve: "trouvé(s)",
        sur: "sur",
        excellent: "✅ Excellent",
        satisfaisant: "⚠️ Satisfaisant",
        ameliorer: "❌ À améliorer",
        modifier: "Modifier",
        annuler: "Annuler",
        sauvegarder: "Sauvegarder",
        confirmer: "Confirmer",
        fermer: "Fermer",
        voir: "Voir",
        succes: "Succès",
        erreur: "Erreur",
        chargement: "Chargement...",
        aucunResultat: "Aucun résultat trouvé.",
        profil: "Profil",
        deconnexion: "Déconnexion",
    },
    aide: {
        titre: "Centre d'aide",
        description: "Guide complet pour utiliser la plateforme MicroFinance Admin",
        recherche: "Rechercher dans l'aide...",
        demarrage: "Démarrage",
        gestionUtilisateurs: "Utilisateurs",
        gestionCredits: "Crédits",
        gestionEpargnes: "Épargnes",
        gestionTransactions: "Transactions",
        gestionParametres: "Paramètres",
        faq: "FAQ",
        astuce: "💡Astuce",
        important: "⚠️Important",
        etape: "étape",
        demarrageTitre: "Bienvenue sur MicroFinance Admin",
        démarrageDesc:
            "Cette plateforme vous permet de gérer l'ensemble des opérations de microfinance pour les commerçants informels au Cameroun.",
        simulationTDB: "Tableau de bord — MicroFinance Admin",
        simulationBonjour: "Salut, Admin",
        simulationDate: "Tableau de bord — Mardi 10 Mars",
        etapesDemarrage: "Étapes de démarrage",
        etape1Titre: "Connectez-vous à votre compte",
        etape1Desc: "Entrez votre email et mot de passe sur la page de connexion.",
        etape2Titre: "Explorez le tableau de bord",
        etape2Desc:
            "Le tableau de bord affiche les statistiques clés : utilisateurs, crédits actifs, épargnes et transactions du jour.",
        etape3Titre: "Naviguez via le menu",
        etape3Desc:
            "Utilisez la barre latérale gauche pour accéder aux différentes sections. Le bouton de déconnexion se trouve en bas de cette barre.",
        etape4Titre: "Personnalisez l'interface",
        etape4Desc: "Dans Paramètres, activez le mode sombre, changez la langue et modifiez votre profil.",
        vueEnsemble: "Vue d'ensemble des sections",
        vueUtilisateurs: "Gérer les commerçants inscrits",
        vueCredits: "Approuver ou rejeter les demandes",
        vueEpargnes: "Suivre les comptes d'épargne",
        vueTransactions: "Historique Orange Money / MTN",
        astuceDeMarrage:
            "Consultez le tableau de bord chaque matin pour avoir une vue d'ensemble des activités de la veille.",
        utilisateursDesc:
            "Cette section vous permet de consulter et gérer tous les commerçants inscrits sur la plateforme.",
        actionsDisponibles: "Actions disponibles",
        uEtape1Titre: "Rechercher un utilisateur",
        uEtape1Desc: "Utilisez la barre de recherche pour trouver un commerçant par nom.",
        uEtape2Titre: "Filtrer par statut",
        uEtape2Desc: "Filtrez la liste par statut : Actif, Inactif ou Suspendu.",
        uEtape3Titre: "Voir le profil",
        uEtape3Desc: "Cliquez sur 'Voir' pour consulter les détails complets d'un commerçant.",
        uEtape4Titre: "Suspendre / Activer",
        uEtape4Desc:
            "Utilisez le bouton 'Suspendre' pour bloquer temporairement un compte, ou 'Activer' pour le réactiver.",
        importantUtilisateurs:
            "La suspension d'un compte empêche le commerçant d'accéder à ses services. Assurez-vous d'avoir une raison valable avant de suspendre un compte.",
        astuceUtilisateurs:
            "Utilisez le filtre 'Suspendu' régulièrement pour vérifier les comptes qui nécessitent une attention particulière.",
        creditsDesc: "Gérez les demandes de microcrédit des commerçants (20 000 — 200 000 FCFA).",
        processusApprobation: "Processus d'approbation",
        cEtape1Titre: "Identifier les demandes en attente",
        cEtape1Desc: "Filtrez par statut 'En attente' pour voir toutes les nouvelles demandes à traiter.",
        cEtape2Titre: "Vérifier les informations",
        cEtape2Desc: "Consultez le montant demandé, le taux d'intérêt et la date d'échéance.",
        cEtape3Titre: "Approuver ou rejeter",
        cEtape3Desc: "Cliquez sur 'Approuver' ou 'Rejeter'. Une modale de confirmation s'affiche avec les détails.",
        cEtape4Titre: "Confirmation",
        cEtape4Desc:
            "Confirmez votre décision. Les fonds sont débloqués sous 24h via Orange Money ou MTN Mobile Money.",
        statutEnCoursDesc: "Crédit actif en cours de remboursement",
        statutEnAttenteDesc: "Demande en attente d'approbation",
        statutEnRetardDesc: "Remboursement en retard — action requise",
        statutRembourseDesc: "Crédit entièrement remboursé",
        importantCredits:
            "Les crédits en retard doivent être traités en priorité. Contactez le commerçant concerné pour trouver une solution.",
        epargnesDesc: "Suivez les comptes d'épargne des commerçants — quotidienne ou hebdomadaire.",
        comprendreEpargnes: "Comprendre les types d'épargne",
        eEtape1Titre: "Épargne quotidienne",
        eEtape1Desc:
            "Le commerçant effectue un dépôt chaque jour. Idéal pour les petits commerçants avec des revenus journaliers.",
        eEtape2Titre: "Épargne hebdomadaire",
        eEtape2Desc: "Le commerçant effectue un dépôt chaque semaine. Adapté aux cycles de vente hebdomadaires.",
        eEtape3Titre: "Suivi de la progression",
        eEtape3Desc:
            "La barre de progression indique le pourcentage atteint par rapport à l'objectif maximum de 200 000 FCFA.",
        eEtape4Titre: "Meilleur épargnant",
        eEtape4Desc: "La bannière dorée met en avant le commerçant ayant le solde d'épargne le plus élevé.",
        astuceEpargnes:
            "Encouragez les commerçants à maintenir une épargne régulière — cela améliore leur score de crédit.",
        transactionsDesc: "Consultez l'historique de toutes les opérations via Orange Money et MTN Mobile Money.",
        typesTransactions: "Types de transactions",
        depotDesc: "Argent déposé sur le compte",
        retraitDesc: "Argent retiré du compte",
        transfertDesc: "Envoi d'argent entre comptes",
        remboursementDesc: "Remboursement d'un crédit",
        canauxPaiement: "Canaux de paiement",
        canalPrincipal: "Canal principal de paiement",
        canalSecondaire: "Canal secondaire de paiement",
        astuceTransactions:
            "Utilisez le double filtre (type + canal) pour analyser rapidement les performances par canal.",
        parametresDesc: "Personnalisez votre expérience sur la plateforme.",
        pProfil: "Profil",
        pProfilDesc: "Modifiez votre nom et email depuis l'onglet Profil en mode édition.",
        pModeSombre: "Mode sombre",
        pModeSombreDesc: "Activez le thème sombre depuis l'onglet Application.",
        pLangue: "Langue",
        pLangueDesc: "Choisissez entre Français, English et Pidgin depuis l'onglet Application.",
        pDeconnexion: "Déconnexion",
        pDeconnexionDesc:
            "Déconnectez-vous via le bouton en bas de la barre latérale gauche ou via le menu profil en haut à droite.",
        changerMotDePasse: "Changer le mot de passe",
        pEtape1Titre: "Accédez à l'onglet Profil",
        pEtape1Desc: "Dans Paramètres, cliquez sur l'onglet 'Profil'.",
        pEtape2Titre: "Activez le mode édition",
        pEtape2Desc: "Cliquez sur 'Modifier' pour passer en mode édition.",
        pEtape3Titre: "Modifiez le mot de passe",
        pEtape3Desc:
            "Cliquez sur 'Modifier le mot de passe', entrez l'ancien puis le nouveau mot de passe (min. 6 caractères).",
        pEtape4Titre: "Sauvegardez",
        pEtape4Desc: "Cliquez sur 'Enregistrer' pour confirmer les changements.",
        deconnexion: "Se déconnecter",
        deconnexionDesc:
            "Vous pouvez vous déconnecter de deux façons : via le bouton 'Se déconnecter' en bas de la barre latérale gauche (icône LogOut), ou via le menu profil en haut à droite du tableau de bord.",
        importantParametres: "Utilisez un mot de passe fort et unique pour sécuriser votre compte administrateur.",
        faqDesc: "Retrouvez les réponses aux questions les plus posées.",
        faq1Q: "Comment me connecter à la plateforme ?",
        faq1R: "Rendez-vous sur la page de connexion, entrez votre email et mot de passe.",
        faq2Q: "Comment approuver une demande de crédit ?",
        faq2R: "Dans la page Crédits, filtrez par 'En attente'. Cliquez sur 'Approuver' à côté de la demande. Une modale de confirmation s'affiche — confirmez pour valider.",
        faq3Q: "Comment me déconnecter ?",
        faq3R: "Deux façons : cliquez sur le bouton 'Se déconnecter' (icône LogOut) en bas de la barre latérale gauche, ou ouvrez le menu profil en haut à droite et cliquez 'Se déconnecter'.",
        faq4Q: "Comment activer le mode sombre ?",
        faq4R: "Allez dans Paramètres → onglet Application. Activez le toggle 'Mode sombre'. Le changement est immédiat et conservé après rechargement.",
        faq5Q: "Comment changer la langue de l'interface ?",
        faq5R: "Allez dans Paramètres → onglet Application. Sélectionnez Français, English ou Pidgin dans le menu Langue.",
        faq6Q: "Que faire si un commerçant ne rembourse pas son crédit ?",
        faq6R: "Identifiez les crédits 'En retard' dans la page Crédits. Consultez les informations du commerçant dans la page Utilisateurs. Si nécessaire, suspendez son compte.",
        faq7Q: "Comment exporter les rapports ?",
        faq7R: "Dans la page Rapports, cliquez sur 'Exporter le rapport' pour télécharger en PDF ou en Excel (CSV).",
        resultatsRecherche: "Résultats pour",
        sections: "Sections",
        aucunResultat: "Aucun résultat trouvé pour cette recherche.",
        besoinAide: "Besoin d'aide supplémentaire ?",
        contactSupport: "Contactez le support technique : support@microfinance.com",
        processusCreation: "Processus de création d'un agent",
        interfaceGestion: "Interface de gestion des agents",
        vueTableau: "Tableau",
        vueCartes: "Cartes",
        redirection: "Redirection vers la liste des agents...",
        agentsTerrain: "Agents de terrain",
    },
    erreurs: {
        champVide: "Ce champ ne peut pas être vide.",
        emailInvalide: "Adresse email invalide.",
        motDePasseCourt: "Le mot de passe doit contenir au moins 6 caractères.",
        motDePasseIncorrect: "L'ancien mot de passe est incorrect.",
        motDePasseNonCorrespondant: "Les mots de passe ne correspondent pas.",
        champsManquants: "Veuillez remplir tous les champs.",
        profilMisAJour: "✅ Profil mis à jour avec succès !",
        motDePasseModifie: "✅ Mot de passe modifié avec succès !",
        notificationsSauvegardees: "✅ Préférences de notifications sauvegardées !",
        parametresSauvegardes: "✅ Paramètres de l'application sauvegardés !",
        erreurGenerale: "❌ Une erreur est survenue.",
    },
    auth: {
        titreConnexion: "MicroFinance Admin",
        sousTitreConnexion: "Espace administrateur sécurisé",
        adresseEmail: "Adresse email",
        motDePasse: "Mot de passe",
        seConnecter: "Se connecter",
        connexionEnCours: "Connexion en cours...",
        accesReserve: "Accès réservé aux administrateurs",
        telephone: "Numéro de téléphone",
        champsObligatoires: "Veuillez remplir tous les champs.",
    },
    notifications: {
        nouveauCredit: "Nouveau crédit en attente",
        creditRetard: "Crédit en retard",
        nouvelUtilisateur: "Nouvel utilisateur inscrit",
        transactionEchouee: "Transaction échouée",
        toutLire: "Tout lire",
        notifications: "Notifications",
        vientDeSInscrire: "vient de s'inscrire depuis",
        ilYa: "il y a",
        minute: "minute",
        minutes: "minutes",
        heure: "heure",
        heures: "heures",
        jour: "jour",
        jours: "jours",
        maintenant: "maintenant",
    },
    agentsTerrain: {
        totalDossiers: "Total dossiers",
        emailPlaceholder: "Saisissez l'adresse email de l'agent",
        listeTitre: "Agents de terrain",
        listeDescription: "Gérez les agents chargés des vérifications sur le terrain.",
        colAgent: "Agent",
        colZone: "Ville",
        colStatut: "Statut",
        colDossiers: "Dossiers",
        colActions: "Actions",
        agents: "agents",
        astuce: "Utilisez le filtre par statut pour identifier rapidement les agents suspendus.",
        etape1Titre: "Accéder à la page Agents",
        etape1Desc: "Dans le menu latéral, cliquez sur 'Agents de terrain'",
        etape2Titre: "Cliquer sur 'Nouvel agent'",
        etape2Desc: "Le bouton vert en haut à droite de la page",
        etape3Titre: "Remplir le formulaire",
        etape3Desc: "Nom, prénom, téléphone, ville, email et mot de passe",
        etape4Titre: "Valider la création",
        etape4Desc: "Cliquez sur 'Créer l'agent' pour finaliser",
        creerTitre: "Créer un nouvel agent",
        titreFormulaire: "Nouvel agent de terrain",
        succesCreation: "✅ Agent créé avec succès !",
        titre: "Créer un agent de terrain",
        sousTitle: "Remplissez les informations pour générer les accès de l'agent.",
        breadcrumb1: "Administration",
        breadcrumb2: "Agents de terrain",
        breadcrumb3: "Nouvel agent",
        apercu: "Prénom et nom de l'agent",
        idAuto: "ID généré automatiquement",
        brouillon: "Brouillon",
        pretACreer: "Prêt à créer",
        identite: "Identité",
        prenom: "Prénom",
        prenomPlaceholder: "Entrez le prénom",
        nom: "Nom ",
        nomPlaceholder: "Entrez le Nom",
        telephone: "Téléphone",
        telephonePlaceholder: "Entrez le  numéro",
        zone: "Ville",
        zoneDefault: "ville",
        zonePlaceholder: "Entrez le nom de sa ville de résidence",
        role: "Rôle",
        roleVerificateur: "Vérificateur",
        roleVerificateurDesc: "Évalue et valide les dossiers de prêt sur le terrain",
        roleCollecteur: "Collecteur",
        roleCollecteurDesc: "Collecte les remboursements et données clients",
        roleSuperviseur: "Superviseur",
        roleSuperviseurDesc: "Supervise et coordonne les agents d'une zone",
        roleComplet: "Accès complet",
        roleCompletDesc: "Toutes les opérations terrain disponibles",
        identifiants: "Identifiants de connexion",
        login: "Identifiant (login)",
        loginHint: "Généré à partir du prénom et du nom",
        motDePasse: "Mot de passe",
        motDePassePlaceholder: "Minimum 8 caractères",
        confirmer: "Confirmer le mot de passe",
        confirmerPlaceholder: "Répéter le mot de passe",
        infoMobile: "L'agent utilisera ces identifiants pour se connecter à l'application mobile.",
        annuler: "Annuler",
        reinitialiser: "Réinitialiser",
        creer: "Créer l'agent",
        errPrenom: "Le prénom est requis",
        errNom: "Le nom est requis",
        errTelephone: "Le téléphone est requis",
        errZone: "Veuillez sélectionner une zone",
        errMotDePasse: "Minimum 8 caractères requis",
        errConfirmer: "Les mots de passe ne correspondent pas",
        forceFaible: "Faible",
        forceMoyen: "Moyen",
        forceBon: "Bon",
        forceExcellent: "Excellent",
        nouvelAgent: "Nouvel agent",
        totalAgents: "Total agents",
        agentsActifs: "Actifs",
        agentsSuspendus: "Suspendus",
        dossiersTraites: "Dossiers traités",
        recherche: "Rechercher par nom, zone ou login...",
        tousStatuts: "Tous les statuts",
        statutActif: "Actif",
        statutSuspendu: "Suspendu",
        tousRoles: "Tous les rôles",
        vueCartes: "Vue cartes",
        aucunAgent: "Aucun agent trouvé.",
        voirProfil: "Voir le profil",
        suspendre: "Suspendre",
        activer: "Activer",
        supprimer: "Supprimer",
        dossiers: "dossiers traités",
        profilTitre: "Profil de l'agent",
        dateInscription: "Inscription",
        confirmerSupprimer: "Supprimer l'agent ?",
        confirmerSuspendre: "Suspendre l'agent ?",
        confirmerActiver: "Activer l'agent ?",
        confirmationTexteSupprimer: "Cette action est irréversible.",
        confirmationTexteStatut: "Vous pouvez modifier ce statut à tout moment.",
    },
};
