export const pidgin = {
  navigation: {
    tableauDeBord: 'Dashboard',
    utilisateurs: 'People Dem',
    credits: 'Loans',
    epargnes: 'Savings',
    transactions: 'Transactions',
    rapports: 'Reports & Statistics',
    aide: 'Help',
    parametres: 'Settings',
    agentsTerrain: 'Fild Agents',
  },
  tableauDeBord: {
    titre: 'Dashboard',
    evolutionDesc: 'Loans, savings and transactions for 6 months',
    cinqDernieresOperations: 'Last 5 operations',
    cinqDerniersMicroCredits: 'Last 5 small loans',
    description:
      'Welcome for your dashboard — see wetin dey happen for platform.',
    totalUtilisateurs: 'All People',
    commercantsInscrits: 'Traders wey register',
    creditsActifs: 'Active Loans',
    pretsEnCours: 'Loans wey dey run',
    epargnesActives: 'Active Savings',
    comptesEpargne: 'Savings accounts',
    transactionsAujourdhui: 'Transactions Today',
    canalsMobile: 'Orange Money & MTN',
    revenusTotal: 'Total Money',
    ceMois: 'Dis month',
    tauxRemboursement: 'Repayment Rate',
    sixDerniersMois: 'For last 6 months',
    evolutionActivites: 'How things dey go (last 6 months)',
    dernieresTransactions: 'Last Transactions',
    creditsRecents: 'Recent Loans',
  },
  utilisateurs: {
    titre: 'People Dem',
    description: 'Manage traders wey register for platform.',
    recherche: 'Find by name, phone or town...',
    tousStatuts: 'All status',
    nom: 'Name',
    telephone: 'Phone',
    ville: 'Town',
    epargne: 'Savings',
    credits: 'Loans',
    statut: 'Status',
    actions: 'Actions',
    aucunUtilisateur: 'No person find.',
    voir: 'See',
    actif: 'Active',
    inactif: 'No active',
    suspendu: 'Block',
    suspendre: 'Block am',
    activer: 'Activate am',
    profil: 'Profile of',
    membreDepuis: 'Member since',
    informationsPersonnelles: 'Personal info',
    donneesFinancieres: 'Money data',
    epargnetotale: 'Total savings',
    creditsActifs: 'Active loans',
    fermerProfil: 'Close profile',
    inscription: 'Registration',
  },
  credits: {
    titre: 'Loans',
    rejete: 'Dem reject am',
    description: 'Manage small loans wey dem give traders.',
    recherche: 'Find by name...',
    tousStatuts: 'All status',
    totalCredits: 'All Loans',
    totalRembourse: 'Money Wey Pay Back',
    enAttente: 'Waiting',
    enRetard: 'Late',
    commercant: 'Trader',
    montant: 'Amount',
    rembourse: 'Pay Back',
    taux: 'Rate',
    echeance: 'Due Date',
    actions: 'Actions',
    aucunCredit: 'No loan find.',
    approuver: 'Approve am',
    rejeter: 'Reject am',
    actif: 'Active',
    rembourse_statut: 'Pay back',
    enAttente_statut: 'Waiting',
    enRetard_statut: 'Late',
    confirmationApprouver: 'You sure say you want approve?',
    confirmationRejeter: 'You sure say you want reject?',
    confirmationTexte: 'Dis action no fit reverse.',
    confirmer: 'Yes, do am',
    annuler: 'No, stop',
    approuverSousTitre: 'Dis action go release di money',
    approuverIntro: 'You wan approve dis request:',
    rejeterIntro: 'You wan reject dis request:',
    approuverAvertissement:
      'Money go release within 24h via Orange Money or MTN Mobile Money.',
    rejeterAvertissement:
      'Di merchant go receive notification. Dis action no fit reverse.',
    confirmerApprobation: 'Yes, approve am',
    confirmerRejet: 'Yes, reject am',
    tauxInteret: 'Interest rate',
    mois: 'month',
    demandes: 'request(s)',
    creditsLabel: 'loan(s)',
    statut: 'Status',
  },
  epargnes: {
    titre: 'Savings',
    description: 'Follow traders savings accounts.',
    recherche: 'Find by name...',
    totalEpargnes: 'All Savings',
    epargnants: 'People Wey Save',
    moyenneParCompte: 'Average per account',
    totalDepots: 'All Deposits',
    meilleurEpargnant: '🏆 Best saver dis month',
    typeEpargne: 'Savings type',
    solde: 'Balance',
    progression: 'Progress',
    nbDepots: 'Nb. Deposits',
    dernierDepot: 'Last Deposit',
    aucuneEpargne: 'No savings find.',
    objectif: 'Target',
    tousTypes: 'All types',
    quotidienne: 'Every day',
    hebdomadaire: 'Every week',
  },
  transactions: {
    titre: 'Transactions',
    description: 'Follow all money wey move for platform.',
    recherche: 'Find by name...',
    totalDepots: 'All Deposits',
    totalTransferts: 'All Transfers',
    totalRetraits: 'All Withdrawals',
    remboursements: 'Pay Back',
    commercant: 'Trader',
    type: 'Type',
    montant: 'Amount',
    canal: 'Channel',
    date: 'Date',
    statut: 'Status',
    aucuneTransaction: 'No transaction find.',
    depot: 'Deposit',
    retrait: 'Withdrawal',
    transfert: 'Transfer',
    remboursement: 'Pay Back',
    reussi: 'E work',
    echoue: 'E no work',
    enAttente: 'Waiting',
    tousTypes: 'All types',
    tousCanaux: 'All channels',
  },
  rapports: {
    titre: 'Reports & Statistics',
    exporter: 'Export',
    sixMois: '6 months',
    volumeCredits: 'Loan Volume',
    totalMicroCredits: 'All small loans',
    totalEpargnes: 'All Savings',
    soldeCumule: 'Total savers money',
    volumeTransactions: 'Transaction Volume',
    toutesOperations: 'All operations',
    tauxReussite: 'Success Rate',
    repartitionCredits: 'Loan Breakdown',
    parStatutRemboursement: 'By repayment status',
    canauxPaiement: 'Payment Channels',
    canauxDesc: 'Orange Money vs MTN Mobile Money',
    nbTransactions: 'Nb. Transactions',
    montantFCFA: 'Amount (FCFA)',
    creditLabel: 'loan(s)',
    tauxRemboursement: 'Repayment rate',
    transactionsReussies: 'Successful transactions',
    epargneReguliere: 'Regular savings',
    creditsEnRetard: 'Late loans',
    description: 'See how platform dey do — January 2025',
    exporterRapport: 'Export report',
    exporterPDF: 'Export as PDF',
    exporterExcel: 'Download Excel table',
    chiffresCles: '📊 Big Numbers',
    chiffresClesDesc: 'Summary of wetin platform do',
    evolutionActivites: '📈 How Things Dey Go',
    evolutionDesc: 'Trends for last 6 months',
    analyseDetaillee: '🔍 Details',
    analyseDesc: 'Loans breakdown and payment channels',
    indicateurs: '🎯 Performance',
    indicateursDesc: 'Key platform rates',
  },
  parametres: {
    titre: 'Settings',
    description: 'Manage your profile and platform preferences.',
    profil: 'Profile',
    notifications: 'Notifications',
    application: 'Application',
    sauvegarderProfil: 'Save profile',
    modifierMotDePasse: 'Change password',
    sauvegarderNotifications: 'Save notifications',
    sauvegarderParametres: 'Save settings',
    langue: 'Interface language',
    devise: 'Currency',
    modifier: 'Change am',
    annuler: 'Leave am',
    sauvegarder: 'Save am',
    modeProfil: 'Change your info.',
    modeProfilLecture: 'See your info.',
    nomComplet: 'Full name',
    email: 'Email',
    telephone: 'Phone',
    motDePasse: 'Password',
    motDePasseDesc: 'Lock your admin access.',
    motDePasseEdition: 'Change your password.',
    motDePasseActuel: 'Current password',
    ancienMotDePasse: '🔑 Old password',
    nouveauMotDePasse: '🆕 New password',
    confirmerMotDePasse: '✅ Confirm password',
    reglesMotDePasse: '📋 Password rules',
    regle1: '✅ At least 6 characters',
    regle2: '✅ Different from old password',
    regle3: '✅ Confirmation must match',
    enLigne: 'Online',
    parametresProfil: 'Profile settings',
    seDeconnecter: 'Comot',
    apparence: '🎨 How e look',
    modeSombre: 'Dark Mode',
    modeClair: 'Light Mode',
    interfaceSombre: 'Dark interface on',
    interfaceClaire: 'Light interface on',
    infoPlateforme: 'ℹ️ Platform info',
    version: 'Version',
    environnement: 'Environment',
    derniereMaj: 'Last update',
    avertissementLangue: '⚠️ Change go apply after you click "Save am".',
    choisirAvatar: '🎭 Pick your avatar',
    changerAvatar: '🎨 Change avatar',
    fermer: '✕ Close',
    notificationsDesc: 'Pick di alerts wey you want receive.',
    applicationDesc: 'Set di theme, language and money.',
    notifNouveauCredit: 'New loan request',
    notifNouveauCreditDesc: 'Alert for every new request',
    notifRemboursement: 'Pay back receive',
    notifRemboursementDesc: 'Confirm payments wey come',
    notifRetard: 'Late loan',
    notifRetardDesc: 'Alert for late payments',
    notifNouvelUtilisateur: 'New person register',
    notifNouvelUtilisateurDesc: 'Alert for every registration',
    notifRapportHebdo: 'Weekly report',
    notifRapportHebdoDesc: 'Auto summary every week',
  },
  commun: {
    actif: 'Active',
    adminDashboard: 'Admin Space',
    rechercher: 'Find...',
    enAttente: 'Pending',
    enCours: 'Active',
    enRetard: 'Late',
    rembourse: 'Paid back',
    suspendu: 'Suspended',
    oui: 'Yes',
    non: 'No',
    locale: 'en-GB',
    masquer: 'Hide',
    afficher: 'Show',
    fermerMenu: 'Close menu',
    menuPrincipal: 'Main menu',
    ouvrirMenu: 'Open menu',
    menuProfil: 'Profile menu',
    administrateur: 'Administrator',
    notificationsNonLues: 'unread notifications',
    bonjour: 'Good morning',
    bonApresMidi: 'Good afternoon',
    bonsoir: 'Good evening',
    filtrer: 'Filter',
    total: 'total',
    trouve: 'find',
    sur: 'of',
    excellent: '✅ Very good',
    satisfaisant: '⚠️ OK',
    ameliorer: '❌ Need work',
    modifier: 'Change am',
    annuler: 'Leave am',
    sauvegarder: 'Save am',
    confirmer: 'Do am',
    fermer: 'Close',
    voir: 'See am',
    succes: 'E work!',
    erreur: 'Problem',
    chargement: 'Wait small...',
    aucunResultat: 'Nothing find.',
    profil: 'Profile',
    deconnexion: 'Comot',
  },
  aide: {
    titre: 'Help Center',
    description: 'Full guide for MicroFinance Admin platform',
    recherche: 'Search help...',
    demarrage: 'Get Started',
    gestionUtilisateurs: 'Users',
    gestionCredits: 'Credits',
    gestionEpargnes: 'Savings',
    gestionTransactions: 'Transactions',
    gestionParametres: 'Settings',
    faq: 'FAQ',
    astuce: '💡 Tip',
    important: '⚠️ Important',
    etape: 'Step',
    demarrageTitre: 'Welcome to MicroFinance Admin',
    démarrageDesc:
      'This platform help you manage all microfinance work for traders for Cameroon.',
    simulationTDB: 'Dashboard — MicroFinance Admin',
    simulationBonjour: 'How now, Admin',
    simulationDate: 'Dashboard — Tuesday March 10',
    etapesDemarrage: 'Steps to start',
    etape1Titre: 'Login your account',
    etape1Desc: 'Put your email and password for login page.',
    etape2Titre: 'Look dashboard',
    etape2Desc:
      'Dashboard show important numbers: users, credits, savings and today transactions.',
    etape3Titre: 'Move around with menu',
    etape3Desc:
      'Use left sidebar to go different sections. Logout button dey for bottom of sidebar.',
    etape4Titre: 'Change how e look',
    etape4Desc:
      'For Settings, you fit turn on dark mode, change language and update your profile.',
    vueEnsemble: 'All sections',
    vueUtilisateurs: 'Manage registered traders',
    vueCredits: 'Approve or reject requests',
    vueEpargnes: 'Follow savings accounts',
    vueTransactions: 'Orange Money / MTN history',
    astuceDeMarrage:
      'Check dashboard every morning to see wetin happen yesterday.',
    utilisateursDesc:
      'This section make you see and manage all traders wey register for platform.',
    actionsDisponibles: 'Wetin you fit do',
    uEtape1Titre: 'Find user',
    uEtape1Desc: 'Use search bar to find trader by name.',
    uEtape2Titre: 'Filter by status',
    uEtape2Desc: 'Filter list by status: Active, Inactive or Suspended.',
    uEtape3Titre: 'See profile',
    uEtape3Desc: "Click 'View' to see full info of trader.",
    uEtape4Titre: 'Suspend / Activate',
    uEtape4Desc:
      "Use 'Suspend' button to block account, or 'Activate' to open am again.",
    importantUtilisateurs:
      'If you suspend account, trader no go fit use services. Make sure you get good reason before you suspend.',
    astuceUtilisateurs:
      "Check 'Suspended' filter regularly to see accounts wey need attention.",
    creditsDesc: 'Manage credit requests from traders (20,000 — 200,000 FCFA).',
    processusApprobation: 'How to approve',
    cEtape1Titre: 'Find pending requests',
    cEtape1Desc: "Filter by 'Pending' to see all new requests wey need action.",
    cEtape2Titre: 'Check information',
    cEtape2Desc: 'Look the amount, interest rate and due date.',
    cEtape3Titre: 'Approve or reject',
    cEtape3Desc:
      "Click 'Approve' or 'Reject'. One confirm window go show with details.",
    cEtape4Titre: 'Confirm',
    cEtape4Desc:
      'Confirm your decision. Money go release within 24h via Orange Money or MTN.',
    statutEnCoursDesc: 'Active credit wey dey repay',
    statutEnAttenteDesc: 'Request wey dey wait for approval',
    statutEnRetardDesc: 'Late repayment — action needed',
    statutRembourseDesc: 'Credit fully paid back',
    importantCredits:
      'Late credits need priority. Contact the trader to find solution.',
    epargnesDesc: 'Follow traders savings accounts — every day or every week.',
    comprendreEpargnes: 'Understand savings types',
    eEtape1Titre: 'Every day savings',
    eEtape1Desc:
      'Trader put money every day. Good for small traders wey get daily income.',
    eEtape2Titre: 'Every week savings',
    eEtape2Desc: 'Trader put money every week. Good for weekly sales cycles.',
    eEtape3Titre: 'Follow progress',
    eEtape3Desc:
      'Progress bar show how far trader don reach towards 200,000 FCFA target.',
    eEtape4Titre: 'Top saver',
    eEtape4Desc: 'Gold banner show trader wey get highest savings balance.',
    astuceEpargnes:
      'Encourage traders to save regular — e go improve their credit score.',
    transactionsDesc:
      'See history of all operations via Orange Money and MTN Mobile Money.',
    typesTransactions: 'Types of transactions',
    depotDesc: 'Money wey enter account',
    retraitDesc: 'Money wey comot from account',
    transfertDesc: 'Money wey move between accounts',
    remboursementDesc: 'Credit repayment',
    canauxPaiement: 'Payment channels',
    canalPrincipal: 'Main payment channel',
    canalSecondaire: 'Second payment channel',
    astuceTransactions:
      'Use double filter (type + channel) to check performance by payment channel.',
    parametresDesc: 'Change how platform look and work for you.',
    pProfil: 'Profile',
    pProfilDesc: 'Change your name and email for Profile tab.',
    pModeSombre: 'Dark mode',
    pModeSombreDesc: 'Turn on dark theme for Application tab.',
    pLangue: 'Language',
    pLangueDesc: 'Choose Français, English or Pidgin for Application tab.',
    pDeconnexion: 'Logout',
    pDeconnexionDesc:
      'Logout through button for bottom of left sidebar or through profile menu for top right.',
    changerMotDePasse: 'Change password',
    pEtape1Titre: 'Go to Profile tab',
    pEtape1Desc: 'For Settings, click Profile tab.',
    pEtape2Titre: 'Turn on edit mode',
    pEtape2Desc: "Click 'Edit' to start editing.",
    pEtape3Titre: 'Change password',
    pEtape3Desc:
      "Click 'Change password', put old password then new one (min. 6 characters).",
    pEtape4Titre: 'Save',
    pEtape4Desc: "Click 'Save' to confirm changes.",
    deconnexion: 'Logout',
    deconnexionDesc:
      "You fit logout two ways: click 'Logout' button for bottom of left sidebar, or open profile menu for top right and click 'Logout'.",
    importantParametres:
      'Use strong password wey no be common one to secure your admin account.',
    faqDesc: 'Find answers to common questions.',
    faq1Q: 'How I go login for platform?',
    faq1R: 'Go login page, put your email and password.',
    faq2Q: 'How I go approve credit request?',
    faq2R:
      "For Credits page, filter by 'Pending'. Click 'Approve' next to request. Confirm window go show — confirm to validate.",
    faq3Q: 'How I go logout?',
    faq3R:
      "Two ways: click 'Logout' button for bottom of left sidebar, or open profile menu for top right and click 'Logout'.",
    faq4Q: 'How I go turn on dark mode?',
    faq4R:
      "Go Settings → Application tab. Turn on 'Dark mode' toggle. Change go happen immediately.",
    faq5Q: 'How I go change language?',
    faq5R:
      'Go Settings → Application tab. Choose Français, English or Pidgin for Language menu.',
    faq6Q: 'Wetin I do if trader no pay back credit?',
    faq6R:
      "Find 'Overdue' credits for Credits page. Check trader info for Users page. If need be, suspend their account.",
    faq7Q: 'How I go export reports?',
    faq7R:
      "For Reports page, click 'Export report' to download as PDF or Excel (CSV).",
    resultatsRecherche: 'Results for',
    sections: 'Sections',
    aucunResultat: 'No results found.',
    besoinAide: 'Need more help?',
    contactSupport: 'Contact support: support@microfinance.com',
    processusCreation: 'How to create agent',
    interfaceGestion: 'How to manage agents',
    vueTableau: 'Table',
    vueCartes: 'Cards',
    redirection: 'Going back to agents list...',
    agentsTerrain: 'Field agents',
  },
  erreurs: {
    champVide: 'Dis field no fit empty.',
    emailInvalide: 'Email no correct.',
    motDePasseCourt: 'Password must reach 6 characters.',
    motDePasseIncorrect: 'Old password no correct.',
    motDePasseNonCorrespondant: 'Passwords no match.',
    champsManquants: 'Fill all fields abeg.',
    profilMisAJour: '✅ Profile don update!',
    motDePasseModifie: '✅ Password don change!',
    notificationsSauvegardees: '✅ Notifications don save!',
    parametresSauvegardes: '✅ Settings don save!',
    erreurGenerale: '❌ Problem happen.',
  },
  auth: {
    titreConnexion: 'MicroFinance Admin',
    sousTitreConnexion: 'Secure admin space',
    adresseEmail: 'Email address',
    motDePasse: 'Password',
    seConnecter: 'Enter',
    connexionEnCours: 'E dey enter...',
    accesReserve: 'Only admin fit enter',
    telephone: 'Phone number',
    champsObligatoires: 'All fields na must.',
  },
  notifications: {
    nouveauCredit: 'New loan dey wait',
    creditRetard: 'Loan don delay',
    nouvelUtilisateur: 'New person don register',
    transactionEchouee: 'Transaction no go through',
    toutLire: 'Read all',
    notifications: 'Notifications',
    vientDeSInscrire: 'just register from',
    ilYa: 'ago',
    minute: 'minute',
    minutes: 'minutes',
    heure: 'hour',
    heures: 'hours',
    jour: 'day',
    jours: 'days',
    maintenant: 'now',
  },

  agentsTerrain: {
    totalDossiers: 'Total dossiers',
    emailPlaceholder: 'Write di agent im email address',
    listeTitre: 'Field Agents',
    listeDescription: 'Manage dem agents wey dey do field work.',
    colAgent: 'Agent',
    colZone: 'Town',
    colStatut: 'Status',
    colDossiers: 'Files',
    colActions: 'Actions',
    agents: 'agents',
    zonePlaceholder: 'Write di name of di town wey e dey stay',
    astuce: 'Use di status filter to see suspended agents quick quick.',
    etape1Titre: 'Go to Agents page',
    etape1Desc: "For sidebar, click 'Field agents'",
    etape2Titre: "Click 'New agent'",
    etape2Desc: 'Di green button for top right of di page',
    etape3Titre: 'Fill di form',
    etape3Desc: 'First name, last name, phone, town, email and password',
    etape4Titre: 'Confirm creation',
    etape4Desc: "Click 'Create agent' to finish",
    creerTitre: 'Create new agent',
    titreFormulaire: 'New field agent',
    succesCreation: '✅ Agent don create!',
    titre: 'Create Fild Agent',
    sousTitle: 'Put di info to give di agent im login.',
    breadcrumb1: 'Admin',
    breadcrumb2: 'Fild Agents',
    breadcrumb3: 'New Agent',
    apercu: 'Agent first and last name',
    idAuto: 'ID go generate automatic',
    brouillon: 'Draft',
    pretACreer: 'Ready to create',
    identite: 'Identity',
    prenom: 'First name',
    prenomPlaceholder: 'e.g. Jean-Pierre',
    nom: 'Last name',
    nomPlaceholder: 'e.g. Mballa',
    telephone: 'Phone',
    telephonePlaceholder: 'e.g. +237 6XX XXX XXX',
    zone: 'Town',
    zoneDefault: 'Pick one zone',
    role: 'Role',
    roleVerificateur: 'Verifier',
    roleVerificateurDesc: 'Check and approve loan papers for field',
    roleCollecteur: 'Collector',
    roleCollecteurDesc: 'Collect payments and client info',
    roleSuperviseur: 'Supervisor',
    roleSuperviseurDesc: 'Oversee and coordinate agents for one zone',
    roleComplet: 'Full Access',
    roleCompletDesc: 'All field operations available',
    identifiants: 'Login Info',
    login: 'Username (login)',
    loginHint: 'Generate from first and last name',
    motDePasse: 'Password',
    motDePassePlaceholder: 'Minimum 8 characters',
    confirmer: 'Confirm password',
    confirmerPlaceholder: 'Repeat di password',
    infoMobile: 'Di agent go use dis login to enter di mobile app.',
    annuler: 'Leave am',
    reinitialiser: 'Reset am',
    creer: 'Create di agent',
    errPrenom: 'First name na must',
    errNom: 'Last name na must',
    errTelephone: 'Phone na must',
    errZone: 'Pick one zone abeg',
    errMotDePasse: 'Minimum 8 characters',
    errConfirmer: 'Passwords no match',
    forceFaible: 'Weak',
    forceMoyen: 'OK',
    forceBon: 'Good',
    forceExcellent: 'Top!',
    nouvelAgent: 'Add new agent',
    totalAgents: 'All agents',
    agentsActifs: 'Active',
    agentsSuspendus: 'Suspended',
    dossiersTraites: 'Files weh dem don treat',
    recherche: 'Search by name, zone or login...',
    tousStatuts: 'All status',
    statutActif: 'Active',
    statutSuspendu: 'Suspended',
    tousRoles: 'All roles',
    vueCartes: 'Card view',
    aucunAgent: 'No agent dey here.',
    voirProfil: 'See profile',
    suspendre: 'Suspend am',
    activer: 'Activate am',
    supprimer: 'Delete am',
    dossiers: 'files dem don treat',
    profilTitre: 'Agent profile',
    dateInscription: 'Date dem register',
    confirmerSupprimer: 'You wan delete dis agent?',
    confirmerSuspendre: 'You wan suspend dis agent?',
    confirmerActiver: 'You wan activate dis agent?',
    confirmationTexteSupprimer: 'Dis action no fit reverse.',
    confirmationTexteStatut: 'You fit change dis status anytime.',
  },
};

export type LanguePidgin = typeof pidgin;
export default pidgin;
